#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""批量生成演示/压测数据（走 /api/v1 接口，与 Flutter 客户端同一契约）。

为什么不直插 SQL：
  轨迹要同时写 trajectories 主表、points_json 大字段、trajectory_points 点表
  三处，且 GPS 点键名是 pts（传 points 会返回 200 但静默落库 0 点——历史坑）。
  走同步接口让服务端自己校验并双写，永远与客户端一致。

用法：
  python scripts/db-gen-data.py --base-url http://127.0.0.1:3000 \
      --users 3 --trips 5 --points 120

  --users N      生成 N 个用户（手机号 1380000xxxx 段，密码 Test123456）
  --trips N      每用户 N 条轨迹
  --points N     每条轨迹 N 个 GPS 点（1~20000，服务端上限）
  --seed S       固定随机种子（可复现；不传则每次随机）
  --prefix P     手机号前缀（默认 138，避免与真实注册账号冲突）

数据特征（有意做出可辨识的分布，方便导入后核对）：
  - 里程 1~15 km、时长 10~120 分钟、海拔爬升 0~600 m，成都周边 GPS 围栏
  - 轨迹标题 demo_<user序号>_<trip序号>，备注带生成时间
"""
import argparse
import json
import random
import sys
import time
import urllib.request
import urllib.error

BASE = "http://127.0.0.1:3000/api/v1"
PASSWORD = "Test123456"

# 成都周边 GPS 围栏（生成的点不会飘到海上）
LAT0, LNG0 = 30.57, 103.95   # 左下角
LAT1, LNG1 = 30.75, 104.20   # 右上角


def http(method: str, path: str, body: dict | None = None, token: str = "") -> dict:
    req = urllib.request.Request(
        BASE + path, method=method,
        data=json.dumps(body).encode() if body is not None else None,
        headers={"Content-Type": "application/json",
                 **({"Authorization": f"Bearer {token}"} if token else {})})
    try:
        with urllib.request.urlopen(req, timeout=15) as r:
            return json.loads(r.read().decode())
    except urllib.error.HTTPError as e:
        detail = e.read().decode()[:200]
        sys.exit(f"✗ {method} {path} → HTTP {e.detail if hasattr(e,'detail') else e.code}\n  {detail}")


def gen_trip(idx: int, rng: random.Random) -> dict:
    """生成一条真实感轨迹：沿随机路线走 N 点，速度/海拔平滑变化。"""
    n = ARGS.points
    start = int(time.time() * 1000) - rng.randint(1, 30) * 86400_000  # 近 30 天内
    duration = rng.randint(600, 7200)                                  # 10~120 分钟
    # 起点随机，之后每步小位移（模拟连续行走而非瞬移）
    lat, lng = rng.uniform(LAT0, LAT1), rng.uniform(LNG0, LNG1)
    pts = []
    for i in range(n):
        ts = start + int(duration * 1000 * i / max(n - 1, 1))
        pts.append({"lat": round(lat, 6), "lng": round(lng, 6), "ts": ts,
                    "alt": round(rng.uniform(480, 1080), 1)})
        lat += rng.uniform(-0.0008, 0.0008)   # ≈ 每步 90m 内
        lng += rng.uniform(-0.0008, 0.0008)
        # 围栏回弹
        lat = min(max(lat, LAT0), LAT1)
        lng = min(max(lng, LNG0), LNG1)
    distance = rng.uniform(1000, 15000)
    return {
        "id": f"demo_{ARGS.phone}_{idx:03d}",
        "start": start,
        "end": start + duration * 1000,
        "distance": round(distance, 1),
        "duration": duration,
        "ascent": round(rng.uniform(0, 600), 1),
        "descent": round(rng.uniform(0, 600), 1),
        "avgSpeed": round(distance / duration * 3.6, 2),
        "title": f"demo_{ARGS.phone}_{idx:03d}",
        "note": f"generated by db-gen-data.py at {time.strftime('%F %T')}",
        "city": "成都",
        "pts": pts,
    }


def main() -> None:
    global ARGS
    ap = argparse.ArgumentParser(description="批量生成演示数据（走 API）")
    ap.add_argument("--base-url", default=BASE)
    ap.add_argument("--users", type=int, default=1)
    ap.add_argument("--trips", type=int, default=3)
    ap.add_argument("--points", type=int, default=60)
    ap.add_argument("--prefix", default="138")
    ap.add_argument("--seed", type=int, default=None)
    ARGS = ap.parse_args()
    base = ARGS.base_url.rstrip("/")
    # 把运行参数挂到全局 ARGS 供 gen_trip 使用（points/phone 前缀等）
    globals()["BASE"] = base

    rng = random.Random(ARGS.seed)   # seed=None 时系统随机
    t0 = time.time()
    ok_users = ok_trips = 0

    for u in range(1, ARGS.users + 1):
        phone = f"{ARGS.prefix}{u:04d}{rng.randint(1000, 9999)}"[:11]  # 3+4+4=11 位
        reg = http("POST", "/auth/register", {
            "phone": phone, "password": PASSWORD, "nickname": f"演示用户{u:02d}"})
        token = reg.get("token", "")
        if not token:
            print(f"✗ 用户 {phone} 注册失败（已存在？）→ 跳过", file=sys.stderr)
            continue
        ok_users += 1

        for t in range(1, ARGS.trips + 1):
            ARGS.phone = phone
            trip = gen_trip(t, rng)
            r = http("POST", "/trajectory/sync", {"trajectory": trip}, token)
            if not r.get("ok"):
                sys.exit(f"✗ 轨迹同步被拒：{r}")
            ok_trips += 1
        print(f"  用户 {phone}：{ARGS.trips} 条轨迹 ✓（最后一条落库 {r.get('points', 0)} 点）")

    print(f"\n完成：{ok_users} 用户 × {ARGS.trips} 轨迹 = {ok_trips} 条，"
          f"耗时 {time.time() - t0:.1f}s")
    print("核对：", "SELECT COUNT(*) FROM trajectories WHERE id LIKE 'demo_%';")


if __name__ == "__main__":
    main()
